# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63035ff614ad6c4dfc54f35196f135a4"
name = "example-header-tutorial"
handle = "example-header-tutorial"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
